import { FacebookIcon } from "../assets/social_media_icons/FacebookIcon";
import { LinkedInIcon } from "../assets/social_media_icons/LinkedInIcon";
import { TwitterIcon } from "../assets/social_media_icons/TwitterIcon";
import { YouTubeIcon } from "../assets/social_media_icons/YouTubeIcon";


// Clients placeholder
const imgStore = "/assets/img/client/";

export const localClients = [
  {
    role: "Autoridad del Canal de Panamá",
    name: "Autoridad del Canal de Panamá",
    imageUrl: `${imgStore}autoridad_del_canal_de_panama.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "Boyd, Barcenas, S.A.",
    name: "Boyd, Barcenas, S.A.",
    imageUrl: `${imgStore}boyd_barcenas_sa.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "Cerebro Y&R",
    name: "Cerebro Y&R",
    imageUrl: `${imgStore}cerebro_yr.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "En Estreno Entertainment",
    name: "En Estreno Entertainment",
    imageUrl: `${imgStore}en_estreno_entertainment.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "E-Motion",
    name: "E-Motion",
    imageUrl: `${imgStore}e_motion.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "Publicis",
    name: "Publicis",
    imageUrl: `${imgStore}publicis.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "Genios",
    name: "Genios",
    imageUrl: `${imgStore}genios.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "Genesis",
    name: "Genesis",
    imageUrl: `${imgStore}genesis.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "In House Advertising",
    name: "In House Advertising",
    imageUrl: `${imgStore}in_house_advertising.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "Insight Advertising",
    name: "Insight Advertising",
    imageUrl: `${imgStore}insight_advertising.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "JW Thompson",
    name: "JW Thompson",
    imageUrl: `${imgStore}jw_thompson.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  // {
  //   role: "Química Publicidad",
  //   name: "Química Publicidad",
  //   imageUrl: `${imgStore}quimica_publicidad.png`,
  //   socialLinks: [
  //     { icon: <FacebookIcon />, duration: 1400 },
  //     { icon: <TwitterIcon />, duration: 1600 },
  //     { icon: <LinkedInIcon />, duration: 1800 },
  //     { icon: <YouTubeIcon />, duration: 1900 },
  //   ],
  //   aosDuration: 1400,
  // },
  {
    role: "Leo Burnett, Panama",
    name: "Leo Burnett, Panama",
    imageUrl: `${imgStore}leo_burnett_panama.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "McCann Erickson Worldgroup Panama",
    name: "McCann Erickson Worldgroup Panama",
    imageUrl: `${imgStore}mccann_erickson_worldgroup_panama.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "MEDCOM",
    name: "MEDCOM",
    imageUrl: `${imgStore}medcom.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  // {
  //   role: "Mega Publicidad",
  //   name: "Mega Publicidad",
  //   imageUrl: `${imgStore}mega_publicidad.png`,
  //   socialLinks: [
  //     { icon: <FacebookIcon />, duration: 1400 },
  //     { icon: <TwitterIcon />, duration: 1600 },
  //     { icon: <LinkedInIcon />, duration: 1800 },
  //     { icon: <YouTubeIcon />, duration: 1900 },
  //   ],
  //   aosDuration: 1400,
  // },
  {
    role: "PISA",
    name: "PISA",
    imageUrl: `${imgStore}pisa.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "Publicuatro",
    name: "Publicuatro",
    imageUrl: `${imgStore}publicuatro.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "Punto Aparte Publicidad",
    name: "Punto Aparte Publicidad",
    imageUrl: `${imgStore}punto_aparte_publicidad.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "RCN-TV",
    name: "RCN-TV",
    imageUrl: `${imgStore}rcn_tv.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "RILA Publicidad",
    name: "RILA Publicidad",
    imageUrl: `${imgStore}rila_publicidad.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  // {
  //   role: "Rogelio Díaz Publicidad",
  //   name: "Rogelio Díaz Publicidad",
  //   imageUrl: `${imgStore}rogelio_diaz_publicidad.png`,
  //   socialLinks: [
  //     { icon: <FacebookIcon />, duration: 1400 },
  //     { icon: <TwitterIcon />, duration: 1600 },
  //     { icon: <LinkedInIcon />, duration: 1800 },
  //     { icon: <YouTubeIcon />, duration: 1900 },
  //   ],
  //   aosDuration: 1400,
  // },
  {
    role: "TBWA/PANAMA",
    name: "TBWA/PANAMA",
    imageUrl: `${imgStore}tbwa_panama.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "Tocumen, S.A.",
    name: "Tocumen, S.A.",
    imageUrl: `${imgStore}tocumen_sa.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "TVN Canal 2",
    name: "TVN Canal 2",
    imageUrl: `${imgStore}tvn_canal_2.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "VFX",
    name: "VFX",
    imageUrl: `${imgStore}vfx.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
];

export const internationalClients = [
  {
    role: "Internacionales",
    name: "BBC-TV",
    imageUrl: `${imgStore}bbc_tv.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "Internacionales",
    name: "BBC-Natural History Unit",
    imageUrl: `${imgStore}bbc_natural_history_unit.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "Internacionales",
    name: "Bunim-Murray Productions (Road Rules Challenge)",
    imageUrl: `${imgStore}bunim_murray_productions_road_rules_challenge.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "Internacionales",
    name: "Crews Control",
    imageUrl: `${imgStore}crews_control.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "Internacionales",
    name: "Darlow-Smithson, Inc.",
    imageUrl: `${imgStore}darlow_smithson_inc.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "Internacionales",
    name: "E! Entertainment Television",
    imageUrl: `${imgStore}e_entertainment_television.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "Internacionales",
    name: "FOX Television",
    imageUrl: `${imgStore}fox_television.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "Internacionales",
    name: "Fremantle Media Argentina (Latin American Idol)",
    imageUrl: `${imgStore}fremantle_media_argentina_latin_american_idol.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "Internacionales",
    name: "Grenada Bristol TV",
    imageUrl: `${imgStore}grenada_bristol_tv.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "Internacionales",
    name: "History Channel",
    imageUrl: `${imgStore}history_channel.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "Internacionales",
    name: "Kaleidescope Pictures",
    imageUrl: `${imgStore}kaleidescope_pictures.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "Internacionales",
    name: "Kingstar TV",
    imageUrl: `${imgStore}kingstar_tv.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "Internacionales",
    name: "Media Arts",
    imageUrl: `${imgStore}media_arts.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  // {
  //   role: "Internacionales",
  //   name: "Miss Universe Inc.",
  //   imageUrl: `${imgStore}miss_universe_inc.png`,
  //   socialLinks: [
  //     { icon: <FacebookIcon />, duration: 1400 },
  //     { icon: <TwitterIcon />, duration: 1600 },
  //     { icon: <LinkedInIcon />, duration: 1800 },
  //     { icon: <YouTubeIcon />, duration: 1900 },
  //   ],
  //   aosDuration: 1400,
  // },
  {
    role: "Internacionales",
    name: "MTV",
    imageUrl: `${imgStore}mtv.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "Internacionales",
    name: "National Geographic Television",
    imageUrl: `${imgStore}national_geographic_television.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "Internacionales",
    name: "NBC'S Today Show Pigeon Productions",
    imageUrl: `${imgStore}nbcs_today_show_pigeon_productions.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "Internacionales",
    name: "Towers Productions",
    imageUrl: `${imgStore}towers_productions.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "Internacionales",
    name: "Twitch Films",
    imageUrl: `${imgStore}twitch_films.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
  {
    role: "Internacionales",
    name: "World Race Productions",
    imageUrl: `${imgStore}world_race_productions.png`,
    socialLinks: [
      { icon: <FacebookIcon />, duration: 1400 },
      { icon: <TwitterIcon />, duration: 1600 },
      { icon: <LinkedInIcon />, duration: 1800 },
      { icon: <YouTubeIcon />, duration: 1900 },
    ],
    aosDuration: 1400,
  },
];
